---
deployment: cf-services-contrib-release

jobs:
- name: micro
  template:
  - redis_gateway
  - redis_node_ng
  properties:
    plan: default
    uaa_client_id: "cf"
    uaa_endpoint: http://uaa.vcap.me
    uaa_client_auth_credentials:
      username: services
      password: c1oudc0w

properties:
  networks:
    apps: default
    management: default

  cc:
    srv_api_uri: http://api.vcap.me

  nats:
    address: 10.10.22.220
    port: 4222
    user: nats
    password: c1oudc0w
    authorization_timeout: 5

  service_plans:
    redis:
      default:
        description: "Developer, 250MB storage, 10 connections"
        free: true
        job_management:
          high_water: 230
          low_water: 20
        configuration:
          capacity: 125
          max_clients: 10
          quota_files: 4
          quota_data_size: 240
          enable_journaling: true
          backup:
            enable: false
          lifecycle:
            enable: false
            serialization: enable
            snapshot:
              quota: 1

  redis_gateway:
    token: c1oudc0w
    default_plan: default
    supported_versions: ["2.6"]
    version_aliases:
      current: "2.6"
    cc_api_version: v2
  redis_node:
    supported_versions: ["2.6"]
    default_version: "2.6"
    max_tmp: 900
